# ============================================================
# Rule: S3 Data Exposure & Exfiltration Detection
# Project: AWS CloudTrail + Elastic SIEM Detection Lab
# Author: Cybernavin
# MITRE ATT&CK: TA0009 (Collection), TA0010 (Exfiltration)
# Severity: High
# Risk Score: 75
# ============================================================

data_stream.dataset:"aws.cloudtrail"
and event.provider:"s3.amazonaws.com"
and event.action:("GetObject" or "PutObject" or "DeleteObject")
and aws.cloudtrail.resources.ARN:*abhinav-sensitive-data-2026*